// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqS3eR4zW62OT1Uf_EZJYau6gdWPzygU',
    appId: '1:297919118149:web:3eab9ac4927db44d27dc2c',
    messagingSenderId: '297919118149',
    projectId: 'boris-flutter-todo-2025',
    authDomain: 'boris-flutter-todo-2025.firebaseapp.com',
    storageBucket: 'boris-flutter-todo-2025.firebasestorage.app',
    measurementId: 'G-48ZYVTT85S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuSnrGaw7DyEg3xg4HlCkIuN9evJ5wuc',
    appId: '1:297919118149:android:ae45de722354b2b827dc2c',
    messagingSenderId: '297919118149',
    projectId: 'boris-flutter-todo-2025',
    storageBucket: 'boris-flutter-todo-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2uu4BIaZwJ1j4s1Qmf4nseTqU-x5yxE',
    appId: '1:297919118149:ios:55ee67a93d808c4827dc2c',
    messagingSenderId: '297919118149',
    projectId: 'boris-flutter-todo-2025',
    storageBucket: 'boris-flutter-todo-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}